--- #YAML:1.0
name:               CPAN-Testers-Reports-Query-JSON
version:            0.04
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    CPAN::Testers::WWW::Reports::Parser:  0.02
    File::Slurp:          0
    JSON::Any:            0
    LWP::Simple:          0
    Moose:                0
    namespace::autoclean:  0.09
    Test::More:           0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
